name: Deploy API (PM2)

on:
  push:
    branches: [main]
    paths:
      - 'packages/api/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    concurrency:
      group: deploy-api
      cancel-in-progress: false

    steps:
      - name: Deploy via git clone + build + pm2
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/ghk
          cd ~/apps
          rm -rf notionblog.com.br
          git clone git@github.com:yagomarinho/notion-blog.git
          cd notionblog.com.br
          yarn
          pm2 stop api
          yarn workspace @notion-blog/api run build
          pm2 restart api
